### ISSUE TITLE
Demo is missing CSS styles

### ISSUE THREAD

**Issue by IAMtheIAM** [krzysu/polymer-shopping-cart#1]
Something is wrong with the demo, the entire site looks messed up,. Missing some stylesheet.

**Comment by krzysu** [comment]
Not sure what was your issue, as I can see it looks fine, as on the screenshot below:

![screen shot 2017-09-28 at 09 49 14](https://user-images.githubusercontent.com/605420/30955007-723bb5fa-a432-11e7-931a-74c0ae3c7505.png)

It's some old material design styles. As you can see this repo was not updated for 3 years, so I would not recommend learning polymer from here anymore.
